### ISSUE TITLE
[Feature Request]:  Commands for EVs

### ISSUE THREAD

**Issue by logal727** [Brandawg93/homebridge-fordpass#164]
### Enhancement of issue

Make more EV related commands. 

### Solution

The Mustang Mach-E doesn't use fuel as we know it, so asking it what the fuel level is doesn't fit. Asking Siri, What is the Charge level of my [vehicle name] would be better. I tried this, but Siri only presents web results. If we can identify fuel value as also charge level that would be sweet. Thank you for this project.

**Comment by Brandawg93** [comment]
Great idea! I've just published v1.6.0-test.0 that gives you the option to customize what you want the battery indicator to be called. You should be able to install it via the `Install Previous Versions` option in the UI. Let me know if this works for you. 

P.S. you may need to clear your accessory cache for this plugin and restart for the name to change.

**Comment by logal727** [comment]
> 

Hmm, for some reason I'm not seeing this in the new feature in 1.6.0 test after installing it. I cleared cache and restarted. I'm on HOOBS. Thanks for the quick response, btw!

**Comment by Brandawg93** [comment]
It should be under the "Advanced Options". I'm not sure how it will look with HOOBS since I use Homebridge. 

https://github.com/Brandawg93/homebridge-fordpass/blob/287bfd39b40e71e9952eebd9467759089978ebd8/config.schema.json#L41

**Comment by logal727** [comment]
Yeah, for some reason it's not updating on the UI, I replaced it with the new config.json file and still doesn't show up under advanced settings, just the usual Auto Refresh options. I wonder if it's because it's a test version. Says this plugin is HOOBS certified too. Everything else works. I can figure it out or wait for another release, no huge deal, thanks for adding it!

**Comment by Brandawg93** [comment]
You may need to install the test version manually. If you can get to a terminal in the UI, you can run `npm i homebridge-fordpass@test`. I don't use HOOBS regularly so I'm not very familiar with it.

**Comment by Brandawg93** [comment]
I just realized in my haste to fix the plugin that I published this in v1.5.2. Whoops...Let me know if it works for you!
