### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gerritg77** [Brandawg93/homebridge-fordpass#195]
### Describe the bug

Unable to connect to Fordpass

### Debug Output

27/7/2022, 10:56:20 amHOOBSFordPassERRORAuth failed with error: ERR_BAD_REQUEST

### Steps to reproduce

1. Configure plugins

### Device Type

raspberry pii

### iOS Version

n/a

### Bug Persistence

Consistently

### Last Working Version

just installed

**Comment by Brandawg93** [comment]
This was fixed in v1.8.0. Are you running the latest version?

**Comment by gerritg77** [comment]
Thanks for responding. I’m running hoobs and it looks like 1.8.0 isn’t available.

thanks.

**Comment by Brandawg93** [comment]
You may need to reach out to their support. They have to update their npm registry. Then you should be able to see the latest version.

**Comment by gerritg77** [comment]
HI MAte.

Sorry to be a pain.. Hoobs is now running 1.8.0 but I’m still getting the same error..  I’d love to get this working so is there any logs etc I can get to help resolve it?


thanks.

**Comment by Brandawg93** [comment]
Check #196
